### ISSUE TITLE
Which version of "Rythm is a Dancer"?

### ISSUE THREAD

**Issue by erl-j** [trumpepsteinaudio/trumpepsteinaudio#1]
There are a couple of versions listed on [wikipedia](https://en.wikipedia.org/wiki/Rhythm_Is_a_Dancer#Track_listing_and_formats), but which one is heard in the recording?

**Comment by trumpepsteinaudio** [comment]
don't know - could use help finding it. I'll add that list to the readme

**Comment by trumpepsteinaudio** [comment]
update- the correct reference track has been found it is in the repo
